# Generated by Django 5.1.4 on 2025-05-14 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BirdSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bird_status', models.CharField(blank=True, choices=[('alive', 'حي'), ('dead', 'نافق')], max_length=10, null=True)),
                ('first_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('cage_count', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
