# Generated by Django 5.1.4 on 2025-05-14 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test0', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='birdsale',
            old_name='cage_count',
            new_name='box_count',
        ),
    ]
