# Generated by Django 5.1.4 on 2025-05-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test0', '0002_rename_cage_count_birdsale_box_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birdsale',
            name='first_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
