# Generated by Django 5.1.4 on 2025-05-14 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test0', '0003_alter_birdsale_first_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=100)),
                ('car_number', models.IntegerField()),
                ('first_wieght', models.CharField(max_length=100)),
                ('trailer_number', models.IntegerField()),
                ('car_type', models.CharField(max_length=100)),
                ('car_adds', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Clint_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clint_id', models.IntegerField()),
                ('clint_name', models.CharField(max_length=100)),
                ('ticket_type', models.CharField(choices=[('Import', 'وارد'), ('Export', 'صادر')], max_length=10)),
                ('category', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('come_from', models.CharField(max_length=100)),
                ('go_to', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Scale_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scale', models.IntegerField()),
                ('scale_time', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='birdsale',
            name='bird_status',
            field=models.CharField(choices=[('alive', 'حي'), ('dead', 'نافق')], default='alive', max_length=10),
        ),
        migrations.AlterField(
            model_name='birdsale',
            name='box_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='birdsale',
            name='first_weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
