# Generated by Django 5.1.4 on 2025-05-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test0', '0004_car_info_clint_file_scale_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clint_file',
            name='category',
            field=models.CharField(choices=[('birds', 'طيور'), ('sheeps', 'اغنام/اخري'), ('dead', 'زراعه')], max_length=100),
        ),
    ]
