# Generated by Django 5.1.4 on 2025-05-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test0', '0005_alter_clint_file_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clint_file',
            name='category',
            field=models.CharField(choices=[('birds', 'طيور'), ('dead', 'زراعه'), ('sheeps', 'اغنام/اخري')], max_length=100),
        ),
    ]
