# Generated by Django 5.1.4 on 2025-05-15 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test0', '0007_scaleinfo_delete_scale_info'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BirdSale',
            new_name='BirdScale',
        ),
    ]
