# Generated by Django 5.1.4 on 2025-05-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test0', '0008_rename_birdsale_birdscale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scaleinfo',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
