# Generated by Django 5.1.4 on 2025-05-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test0', '0009_alter_scaleinfo_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scaleinfo',
            name='created_at',
            field=models.CharField(),
        ),
    ]
